[workspace]
members = [
    "helixui-lib",
    "helixui-website",
]
resolver = "2"

[workspace.package]
version = "0.1.1"
authors = ["fangbaichun <fangbaichun@beemwork.com>"]
edition = "2021"

[workspace.dependencies]
dioxus = "0.7.0-rc.3"
dioxus-time = { git = "https://github.com/ealmloff/dioxus-std", branch = "0.7" }
tracing = { version = "0.1", features = ["std"] }
tokio = { version = "1.43.0", features = ["time"]}
time = { version = "0.3.41", features = ["std", "macros", "parsing"] }
gloo-timers = { version = "0.3.0", features = ["futures"] }
futures = "0.3.31"
futures-util = "0.3.31"
js-sys = "0.3.77"
web-sys = { version = "0.3", features = ["Window", "Navigator", "Clipboard"] }
wasm-bindgen-futures = "0.4"
arboard = "3"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
