[workspace]
members = [
    "helixui-lib",
    "helixui-website",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["fangbaichun <fangbaichun@beemwork.com>"]
edition = "2021"

[workspace.dependencies]
dioxus = "0.7.0-rc.3"
tracing = { version = "0.1", features = ["std"] }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
